apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd-cloudwatch.fullname" . }}
  labels:
    app: {{ template "fluentd-cloudwatch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.awsAccessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.awsSecretAccessKey | b64enc }}
